---
# file: config.yml
#
# Druid configurations:
- name: Copy common.properties for Druid node {{ druid_role }}
  template:
    src: _common/common.runtime.properties.j2
    dest: "{{ druid_path }}conf/druid/_common/common.runtime.properties"
    owner: "{{ druid_user }}"
    mode: 0755
  become: yes

- name: Copy core-site.xml for Druid node {{ druid_role }}
  template:
    src: _common/core-site.xml.j2
    dest: "{{ druid_path }}conf/druid/_common/core-site.xml"
    owner: "{{ druid_user }}"
    mode: 0755
  become: yes

- name: Remove _common log4j2.xml file
  file:
    state: absent
    path: "{{ druid_path }}conf/druid/_common/log4j2.xml"

- name: Copy log4j2.xml for Druid node {{ druid_role }}
  template:
    src: _common/log4j2.xml.j2
    dest: "{{ druid_path }}conf/druid/{{ druid_role }}/log4j2.xml"
    owner: "{{ druid_user }}"
    mode: 0755
  become: yes

- block:
  - name: Make sure the graphite emitter conf directory exists
    file:
      path: "{{ druid_path }}conf/druid/_common/emitter/graphite"
      state: directory
      owner: "{{ druid_user }}"
      mode: 0755
    become: yes

  - name: Copy over the the graphite metric whitelist file
    template:
      src: "_common/emitter/graphite/metric-whitelist.json.j2"
      dest: "{{ druid_path }}conf/druid/_common/emitter/graphite/metric-whitelist.json"
      owner: "{{ druid_user }}"
      mode: 0755
    become: yes
  when: druid_emitter == "graphite" and druid_emitter_graphite_metric_whitelist != ""

- name: Copy over specific configuration for Druid node {{ druid_role }}
  template:
    src: "{{ druid_role }}/runtime.properties"
    dest: "{{ druid_path }}conf/druid/{{ druid_role }}/"
    owner: "{{ druid_user }}"
    mode: 0755
  become: yes

- name: Copy over jvm configuration for Druid node {{ druid_role }}
  template:
    src: "{{ druid_role }}/jvm.config"
    dest: "{{ druid_path }}conf/druid/{{ druid_role }}/"
    owner: "{{ druid_user }}"
    mode: 0755
  become: yes

- name: Copy over systemd service file for druid role {{ druid_role }}
  template:
    src: druid.service.j2
    dest: /lib/systemd/system/druid-{{ druid_role }}.service
    owner: root
    mode: 0644
  become: true

- name: Start druid {{ druid_role }} systemd service
  systemd:
    name: druid-{{ druid_role }}
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
